# config.yml —— 所有配置集中于此
uuid: "4fac55fa-2789-4e48-b8df-ad87d36a332a"                       #输入uuid
tuic_port: "25602"                  #输入端口=确认部署
hy2_port: "25602"                   #输入端口=确认部署
reality_port: "25602"               #输入端口=确认部署
sni: "104.194.9.135"
